version: '3.8'
services:
    php-fpm:
        build:
            context: ./php-fpm
        restart: always
        volumes: 
            - ./src/:/var/www/html/
            - ./logs/php/:/logs/
            - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini
    mariadb:
        image: mariadb:10.5.5
        container_name: mariadb
        restart: always
        environment:
            MYSQL_USER: administrador 
            MYSQL_PASSWORD: SeremiInfo05
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: lme5
        volumes:
            - "./mariadb/:/var/lib/mysql"
        ports: 
            - "3307:3306"
    phpmyadmin:
        image: phpmyadmin
        environment: 
            PMA_HOST: mariadb
    nginx:
        restart: always
        build: 
            context: ./nginx
        ports: 
            - '80:80'
        volumes: 
            - ./src/:/var/www/html/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
    angular:
        restart: always
        build:
            context: ./node
        volumes:
            - ./src/frontend:/var/www/html/